pkg/query/ast.go

Since we were repeatedly incrementing the same time.Time struct, if we had a large gap in data, you could end up in the situation where you get multiple samples from within the same sample period. Instead, let's always increment the last matched time.Time struct.

Fix a bug where sample may not work if large gaps in the data exists.

---

cmd/fossil/client/client.go

* Introduce a `QUIT` pseudo-command
* Ensure that the client is well-behaved when piping data into the command
For example, things like this now work nicely:
```
λ › echo "QUERY all" | ./fossil client -H fossil://localhost:8001                                                                                    Projects/fossil dev/client-papercuts
2022-11-29 16:07:43.458014923 -0800 PST	/	foo
2022-11-29 16:08:06.661906812 -0800 PST	/	foo
2022-11-29 16:08:09.736406357 -0800 PST	/	foo
2022-11-29 16:08:11.121007235 -0800 PST	/	foo
2022-11-29 16:08:56.432017214 -0800 PST	/	foo
2022-11-29 17:33:55.837350118 -0800 PST	/	bar
2022-11-29 17:35:31.820416142 -0800 PST	/	thisiscool!
2022-11-29 20:00:49.934418272 -0800 PST	/	wow
2022-11-29 20:00:56.678709179 -0800 PST	/	such fun
2022-11-29 …
```

Fix a couple of papercuts with `fossil client`

---

pkg/database/db.go
pkg/database/log.go
pkg/database/segment.go
pkg/database/segment_test.go

Since slices are passed by reference and not value, we need to explicitly `copy()` the slice before inserting it into our in-memory database. Since the write-ahead-log uses the gob serializer, that was already copying the slice for us, meaning that the log was never corrupted.
Aside: the github-generated name for this branch is ridiculous

Internals: Append needs to copy passed in `[]byte` data

---

.gitignore
README.md
cmd/fossil/client/client.go
cmd/fossil/config.go
cmd/fossil/root.go
cmd/fossil/server/server.go
cmd/fossil/test/test.go
config.default.toml
docs/overview.md
pkg/database/db.go
pkg/database/log.go
pkg/database/segment.go
pkg/database/segment_test.go
pkg/server/server.go

#19 
This is a big one, and might need a few more changes. There is an output trace below of how the config is loaded, we will likely want to build an object to pass to database or have some other logic mapping databases to their files.
```shell
❯ go run main.go -vvv client -c ./config.default.toml
2022-11-30T23:32:06-05:00 TRC cmd/fossil/config.go:51 > database.default.path = data/default.log
2022-11-30T23:32:06-05:00 TRC cmd/fossil/config.go:47 > database.test.path = data/test.log
2022-11-30T23:32:06-05:00 TRC cmd/fossil/config.go:102 > database.names=[tester test default]
2022-11-30T23:32:06-05:00 TRC cmd/fossil/config.go:102 > fossil.prom-port=2112
2022-11-30T23:32:06-05:00 TRC cmd/fossil/config.go:102 > fossil.host=fossil://local/default
2022-11-30T23:32:06-05:00 TRC …
```

Refactor configuration loading

---

docs/grammar.md
pkg/database/db.go
pkg/database/query.go
pkg/query/ast.go
pkg/query/parser.go
pkg/query/parser_test.go
pkg/query/scanner.go
pkg/query/scanner_test.go
pkg/query/token.go

This PR:
* Implements time-predicates
* Improves sample() to take a time-quantity (instead of just a timespan)
* Fixes a few retrieval accuracy bugs, [see this commit](https://github.com/dburkart/fossil/pull/39/commits/03bcf74118d5f699a0ecdee5677108019697903f) for more context
* Changes the grammar slightly for usability reasons

Implement time-predicate support

---

cmd/fossil/client/client.go
pkg/proto/message.go
pkg/proto/responseWriter.go
pkg/query/parser.go
pkg/query/parser_test.go
pkg/query/prepare.go
pkg/query/scanner.go
pkg/query/token.go
pkg/server/mux.go
pkg/server/server.go

Instead of panicking on a string, we panic using a new `SyntaxError` struct, which records the location and error message. Further, in the `Parse()` function, instead of simply printing out the error, we instead set the error being returned to a formatted error message which includes context.
This resolves issue #43

Bubble syntax errors up to clients

---

pkg/query/ast.go
pkg/query/parser.go
pkg/query/parser_test.go
pkg/query/scanner.go
pkg/query/times.go

This adds support for a variety of date / time layouts that are now usable in a custom whence (`~(...)`). For example, the following now works, among a host of other possible layouts:
```
> QUERY all since ~(2022/12/05)
2022-12-06T09:48:04-08:00 TRC cmd/fossil/client/client.go:99 > message sent bytes=33
+------------------------------------+-------+----------------------+
|                TIME                | TOPIC |         DATA         |
+------------------------------------+-------+----------------------+
| 2022-12-06T09:47:48.51024114-08:00 | /foo  | new day, new message |
+------------------------------------+-------+----------------------+
> QUERY all since ~(2022/12/04)
2022-12-06T09:48:14-08:00 TRC cmd/fossil/client/client.go:99 > message sent bytes=33 …
```

Support flexible date / times in the whence construction

---

pkg/query/parser.go
pkg/query/parser_test.go

Realistically, having "queries that begin with valid syntax" being accepted by the parser seems terrible.

The query parser should fail if the whole input was not consumed.

---

api/api.go
cmd/fossil/client/client.go
pkg/proto/command.go
pkg/proto/message.go
pkg/proto/message_test.go
pkg/repl/parser.go
pkg/server/server.go

This closes #57.
In this PR, we add support for:
* A "version" command
* VersionRequest / VersionResponse messages
This does not add any logic around rejecting / accepting particular versions of the fossil protocol; all versions are accepted by both client and server.
However, by adding this functionality before our first version, we'll be able to easily discover the version of a client / server in the future.

Protocol version advertisement

---

pkg/database/db.go
pkg/query/ast.go
pkg/server/server.go

Since we were using a map to do quick lookups of topic indices, we could get into a situation where the map would change out from under a reader, since maps are not thread safe.
This change moves Database.Topics to be a private map, Database.topics, and protects all private usage with a `sync.RWMutex`. All external usage of topics must make use of Database.TopicLookup, which is a slice (and thus safe in Go).
In the future we can consider implementing a public API on a Database object to allow for faster lookups that enforces using the RWLock.
closes #81

Fix for a concurrency bug related to database topic lookup.

---

pkg/database/db.go

Turns out we weren't initializing our private topic map in this case.
closes #87

Fix a crash when reading from a database which as spilled it's log.

---

pkg/database/db.go

Always apply the write-ahead-log when creating a new db.

---

api/api.go
cmd/fossil/client/client.go

We only try this in the following error scenarios:
* We got an EOF when reading data
* We got a connection reset error
* We got a pipe closed error
In the above scenarios, we will now attempt to replace the bad net.Conn from our pool with a good one using a new reconnection method.
I'm not sure if the time makes sense-- the backoff will wait for 1 second, then 2 seconds, then 4, and then give up. I'm not sure if those units of time are ideal or not, so that's worth a discussion.
closes #79

Implement exponential backoff to try reconnecting to a lost server.

---

pkg/proto/message.go

This switches the fossil server protocol to expect network order, and send responses in network order as well. This allows clients to use the BSD-style hton*, ntoh* family of functions to implement the protocol.
closes #98

Switch protocol to use BigEndian when sending data over the network.

---

pkg/database/db.go
pkg/database/migration.go
pkg/database/stats.go

Previously, we wrote a gobb'd version of the database to disk. This changes that so we now write the following files to our database directory:
* metadata
* topics
* segments/{0..N}
The metadata file now holds metadata about our database, including it's version, the number of segments, the current segment, and the last serialize time (recorded in the struct as STime).
The topics file contains a serialized list of topics, in index-order.
A new segments directory contains one file per segment, which allows us to write out only the most recent segment(s), instead of needing to write out the entire in-memory database.
closes #18

Implement non-gobbed database format

---

pkg/proto/message.go

In the future, we can make this configurable as part of #99 
closes #103

Constrain individual messages to be 100 MiB.

---

docs/schema.md
pkg/database/db.go
pkg/database/log.go
pkg/database/migration.go
pkg/schema/objects.go
pkg/schema/objects_test.go
pkg/schema/parser.go
pkg/schema/parser_test.go
pkg/schema/scanner.go
pkg/schema/scanner_test.go

This PR covers these changes:
* Rename "shallow map" to "composite", since it's really just a composite type
* Teach schema.Object how to marshal itself as JSON
* The database now tracks what schema a given topic has, and defaults it to "string"
This closes #17, but we still have to support topic creation (with ability to specify a schema) in #108.

Remainder of database support for schemas

---

cmd/fossil/client/client.go
pkg/database/db.go
pkg/database/result.go
pkg/proto/command.go
pkg/proto/message.go
pkg/proto/message_test.go
pkg/repl/parser.go
pkg/server/server.go

This PR includes the following:
* Logic in the protocol for creating new topics (and their associated schemas)
* A new "create topic" command in the REPL
* Plumbs logic through database internals for validating new schemas against existing topic hierarchies.
closes #108

Teach the server and client how to create new topics and schemas

---

LICENSE
README.md
api/api.go
cmd/fossil/client/client.go
cmd/fossil/root.go
config.default.toml
pkg/database/db.go
pkg/proto/connectionstring.go
pkg/proto/connectionstring_test.go
pkg/server/server.go

Instead of rolling our own URL parsing, use url.Parse(). In addition,
this patch changes some of the URL behavior:
* We now support file:// protocol
* Gone is the "local" specifier, i.e. fossil://local/foo or local/foo.
Instead, users can either write ./path/to/foo or file://./path/to/foo
* CreateDatabase() now expects the "location" argument to fully
resolve to the database in question. Previously, it would slap
together the location and the name. Internally, the database name is
not used, so it doesn't make sense to have that logic live in
CreateDatabase.

Use url.Parse() to parse fossil urls.

---

docs/grammar.md
docs/pipelines.md

Data predicates essentially act as a filter on data. With data pipelines, filtering is still possible, but much more is possible as well through use of "map" and "reduce" style data functions.

Docs: Replace data predicates with data pipelines.

---

api/encode.go
cmd/fossil/client/client.go
docs/grammar.md
pkg/repl/parser.go
pkg/repl/parser_test.go

This implements sending everything but composites. Demo:
```
> create topic /sensors/temp float32
200 Ok
> list schemas
/sensors/temp float32
> append /sensors/temp 55.6
200 Ok
> query all
+-------------------------------------+---------------+--------------------+
|                TIME                 |     TOPIC     |        DATA        |
+-------------------------------------+---------------+--------------------+
| 2023-01-03T13:09:25.218208875-08:00 | /sensors/temp | float32(55.599998) |
+-------------------------------------+---------------+--------------------+
> exit
```
and arrays:
```
> create topic /points [2]int32
200 Ok
> list schemas
/sensors/temp float32
/points [2]int32
> append /points 1000, 2000
200 Ok
> query all …
```

Support for appending structured data in the client

---

pkg/query/plan/function.go
pkg/query/plan/pipeline.go
pkg/query/types/value.go

This allows tuples to flow through a pipeline. For example, this kind of thing is now possible:
```
> query all x in /numbers : map x -> 1, x
+----------------------------------+----------+----------+-------+
|               TIME               |  TOPIC   |  SCHEMA  | DATA  |
+----------------------------------+----------+----------+-------+
| 2023-01-12T16:17:33.742625-08:00 | /numbers | [2]int64 | 1, 1  |
| 2023-01-12T16:17:35.52783-08:00  | /numbers | [2]int64 | 1, 2  |
| 2023-01-12T16:17:42.102728-08:00 | /numbers | [2]int64 | 1, 3  |
| 2023-01-12T16:17:43.302907-08:00 | /numbers | [2]int64 | 1, 4  |
| 2023-01-12T16:17:44.604381-08:00 | /numbers | [2]int64 | 1, 5  |
| 2023-01-12T16:17:45.751371-08:00 | /numbers | [2]int64 | 1, 6  |
| 2023-01-12T16:17:46.846735-08:00 | /numbers | …
```

Support tuple values in the pipeline backend
